version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - .:/var/www:delegated
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost remote_enable=1 profiler_enable_trigger=1 profiler_output_dir=/var/www/storage/profile"
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www
    networks:
      - platform
  postgres:
    container_name: postgres-urlsrotener
    image: postgres:12.3
    ports:
      - 5433:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
    networks:
      - platform
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    working_dir: /var/www
    depends_on:
      - app
    volumes:
      - .:/var/www:delegated
    ports:
      - 8080:80
    networks:
      - platform

volumes:
  data-postgres:
networks:
  platform:

